### ISSUE TITLE
how to set the startup file

### ISSUE THREAD

**Issue by hzjsea** [ClericPy/zipapps#1]
![image](https://user-images.githubusercontent.com/61597549/102567050-adc19700-411b-11eb-9317-2c9ef52f3cbe.png)
![image](https://user-images.githubusercontent.com/61597549/102567099-c16cfd80-411b-11eb-9802-96c705a4dc27.png)
![image](https://user-images.githubusercontent.com/61597549/102567118-cd58bf80-411b-11eb-972a-48886a78e3a4.png)
![image](https://user-images.githubusercontent.com/61597549/102567139-d8135480-411b-11eb-801a-43d765c80fd9.png)

Can you help me thanks

**Comment by ClericPy** [comment]
Hi @hzjsea ,
`-a app2` will add the folder to pyz file

**Comment by hzjsea** [comment]
> @hzjsea，您好，
> `-a`arg将帮助您向pyz添加一些文件或文件夹。如果您还有其他要求（例如应用程序），也应该添加它们。

thanks
