### ISSUE TITLE
py to pyc

### ISSUE THREAD

**Issue by qbit-git** [ClericPy/zipapps#7]
Could you compile py to pyc and then zip pyc to pyz?

**Comment by ClericPy** [comment]
```
-cc, --pyc, --compile, --compiled
Compile .py to .pyc for fast import, but zipapp does not work unless you unzip it(so NOT very useful).
the compiled arg of zipapps.create_app
```
Is this arg?

**Comment by ClericPy** [comment]
or `-a xxx.pyc` is also worked

**Comment by qbit-git** [comment]
Can use `py_compile.compile`. example:
``` python
def Main():
    for parent, dirnames, filenames in os.walk(SrcDir):
        for filename in filenames:
            extName = pathlib.Path(filename).suffix
            if extName not in {'.py', '.pyd', '.pyi', '.pyx', '.pem'}:
                continue
            srcFile = os.path.join(parent, filename)
            if IsIgnoreDir(parent):
                logger.info(f'Ignore {srcFile}')
                continue
            dstFile = os.path.join(CacheDir, srcFile[len(SrcDir)+1:])
            dstDir = os.path.dirname(dstFile)
            if not os.path.exists(dstDir):
                os.makedirs(dstDir)
            if extName == '.py':
                logger.info(f'Compile {srcFile} ...')
                dstFile = f'{dstFile}c'
                py_compile.compile(srcFile, dstFile)
            else:
                logger.info(f'Copy {srcFile} ...')
                shutil.copyfile(srcFile, dstFile)
    logger.info(f'Create {PyzFileName} ...')
    zipapp.create_archive(CacheDir, PyzFileName, main='main:main')
```

**Comment by ClericPy** [comment]
zipapp is not my lib, do you want to use `zipapps` instead of `zipapp`?

**Comment by qbit-git** [comment]
zipapp is a python standard lib. I only want you package pyz after compile py to pyc.

**Comment by ClericPy** [comment]
`zipapps` depends on `zipapp` indeedly

For I don't know what's your dir tree looks like, so try this:

`python3 -m zipapps -c -m main:main -a {SrcDir} -o {PyzFileName} -u AUTO -r requirements.txt`

`*.pyd` will be unzipped while running

**Comment by qbit-git** [comment]
`--pyc` cannot work.
```
python -m zipapps -c --pyc -d -a test.py -m test:test -o app.pyz requests
========== Start building `app.pyz` with zipapps version <2021.04.29> ==========
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\lib\site-packages\zipapps\__main__.py", line 228, in <module>
    main()
  File "C:\Python39\lib\site-packages\zipapps\__main__.py", line 204, in main
    return create_app(
  File "C:\Python39\lib\site-packages\zipapps\main.py", line 379, in create_app
    return ZipApp.create_app(*args, **kwargs)
  File "C:\Python39\lib\site-packages\zipapps\main.py", line 359, in create_app
    return app.build()
  File "C:\Python39\lib\site-packages\zipapps\main.py", line 160, in build
    self.ensure_args()
  File "C:\Python39\lib\site-packages\zipapps\main.py", line 120, in ensure_args
    raise ValueError(
ValueError: The arg `compiled` should not be True while `unzip` is null, because .pyc files of __pycache__ folder may not work in zip file.
========== Build failed ==========
```

**Comment by ClericPy** [comment]
The arg `compiled` should not be True while `unzip` is null, because .pyc files of __pycache__ folder may not work in zip file.

add
`-u="*"` or `-u AUTO`

**Comment by qbit-git** [comment]
It still doesn't work. Could test with my code?
`test.py`
```
import requests

def test():
    r = requests.get(r'https://www.httpbin.org/get')
    print(r)

if __name__ == '__main__':
    test()
```

**Comment by qbit-git** [comment]
@ClericPy 
I saw your code. You use `compileall`, it will create `__pycache__`. If use py_compile.compile for sigle py file and keep original directory structure, it will be work well. No `__pycache__`.

**Comment by ClericPy** [comment]
Good idea. I will try your opinion later, thanks.

I follow the usage from `shiv` compile_pyc, but that lib will unzip all the time. This is the difference.

**Comment by ClericPy** [comment]
Could you tell that what's the main advantage of `pyc`? I didn't think that has great benefits yet.

**Comment by qbit-git** [comment]
I tried [shiv](https://github.com/linkedin/shiv) and [pex](https://github.com/pantsbuild/pex). I don't think either one works very well. 
I hope you can make a cli tool.
I also hope you can pack with pyproject.toml, like work with [peotry](https://github.com/python-poetry/poetry).
Sorry, I want a little too much.:joy:

**Comment by qbit-git** [comment]
I have two reason for pyc:
1、fast
2、mild encrypt

**Comment by ClericPy** [comment]
This lib will `not` depend on any 3rd requirements to keep it simple, you can fork and try those features.

And, I thought `.pyc` only for `loading` faster but not `running` faster. Besides, decompile pyc files is not very difficult for now (many libs can do). So these two reasons may not impress me.

**Comment by qbit-git** [comment]
I tried some lib to decompile pyc. It does restore clearly. It's enough for my specific situation. 
Dont get overly concerned with my feature requestd.These are my own thoughts ：）
I don't have the ability to create a common lib yet. 
Thanks for your time.

**Comment by ClericPy** [comment]
You're welcome and truely give me some help.  I use `zipapps` in my work for half a year (same long time for `shiv`) and have no more `Constructive ideas` for weeks.

People who use pure Python actually rarely care about performance and encryption. Many people who care about those factors would rather choose Cython or golang... `pyc` is good but not good enough, and these days I am more interested in nuitka...

Thanks for your time too ^-^.

**Comment by qbit-git** [comment]
Thank you give me a new tool [nuitka](https://github.com/Nuitka/Nuitka).  I only used [pyinstasller](https://github.com/pyinstaller/pyinstaller) before in the same tools. In many cases， people just want better platform compatibility and easy to use, like java's jar.

**Comment by Ali8586** [comment]
how to cython decompile

**Comment by ClericPy** [comment]
> how to cython decompile

I don't know either.
